"""v3.1 foundation kernel authority primitives.

Legacy domain modules remain useful adapters and projections. This package is
the first v3.1 authoritative command/event/capability/budget/side-effect spine.
"""

from .records import (
    ArtifactRef,
    Budget,
    CapabilityGrant,
    ClaimRecord,
    Command,
    Decision,
    EvidenceBundle,
    Event,
    HoldoutPolicy,
    HoldoutUseRecord,
    LocalOffloadEvalSet,
    ModelCandidate,
    ModelDemotionRecord,
    ModelEvalRun,
    ModelPromotionDecisionPacket,
    ModelRouteDecision,
    ModelTaskClassRecord,
    OpportunityProjectDecisionPacket,
    ResearchRequest,
    SourceAcquisitionCheck,
    SourcePlan,
    SideEffectIntent,
    SideEffectReceipt,
    SourceRecord,
)
from .commercial import (
    KernelCommercialResearchWorkflow,
    commercial_decision_packet_command,
)
from .model_intelligence import (
    KernelModelIntelligence,
    SEED_TASK_CLASSES,
    ShadowExecutionRecord,
    ShadowExecutionResult,
    ShadowOutputArtifact,
    ShadowOutputSample,
    default_seed_task_classes,
    model_intelligence_command,
)
from .research import (
    KernelResearchEngine,
    LegacyResearchProjection,
    evidence_bundle_command,
    research_request_command,
    retrieval_grant_command,
    source_acquisition_command,
    source_plan_command,
)
from .store import (
    LEGACY_BOUNDARIES,
    KernelStore,
    KernelTransaction,
    ReplayState,
    create_kernel_database,
)
from .runtime import (
    KernelRuntime,
    PreparedProviderCall,
    ProviderCallRequest,
    RuntimeBootstrapState,
    bootstrap_runtime_state,
    make_session_context,
    migrate_runtime_databases,
    normalize_runtime_layout,
    prepare_runtime_directories,
    require_runtime_databases,
    runtime_logs_dir,
    verify_runtime_databases,
)

__all__ = [
    "ArtifactRef",
    "Budget",
    "CapabilityGrant",
    "ClaimRecord",
    "Command",
    "Decision",
    "EvidenceBundle",
    "Event",
    "HoldoutPolicy",
    "HoldoutUseRecord",
    "KernelModelIntelligence",
    "KernelStore",
    "KernelTransaction",
    "KernelResearchEngine",
    "KernelCommercialResearchWorkflow",
    "KernelRuntime",
    "LEGACY_BOUNDARIES",
    "LegacyResearchProjection",
    "LocalOffloadEvalSet",
    "ModelCandidate",
    "ModelDemotionRecord",
    "ModelEvalRun",
    "ModelPromotionDecisionPacket",
    "ModelRouteDecision",
    "ModelTaskClassRecord",
    "OpportunityProjectDecisionPacket",
    "PreparedProviderCall",
    "ProviderCallRequest",
    "ReplayState",
    "ResearchRequest",
    "RuntimeBootstrapState",
    "SEED_TASK_CLASSES",
    "ShadowExecutionRecord",
    "ShadowExecutionResult",
    "ShadowOutputArtifact",
    "ShadowOutputSample",
    "SideEffectIntent",
    "SideEffectReceipt",
    "SourceAcquisitionCheck",
    "SourcePlan",
    "SourceRecord",
    "bootstrap_runtime_state",
    "create_kernel_database",
    "commercial_decision_packet_command",
    "evidence_bundle_command",
    "default_seed_task_classes",
    "make_session_context",
    "migrate_runtime_databases",
    "model_intelligence_command",
    "normalize_runtime_layout",
    "prepare_runtime_directories",
    "require_runtime_databases",
    "runtime_logs_dir",
    "research_request_command",
    "retrieval_grant_command",
    "source_acquisition_command",
    "source_plan_command",
    "verify_runtime_databases",
]
